trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /sast-demo/*

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    sast-demo:
      dockerfile-path: ./sast-demo
      image-name: $IMAGE_NAME

variables:
  - group: "SAST Demo Variables"

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: "17.09.0-ce"

  - script: docker login -u $(IMAGE_REGISTRY_USERNAME) -p $(IMAGE_REGISTRY_PASSWORD) $IMAGE_REGISTRY
    displayName: Docker Login

  - script: docker build $(dockerfile-path) --tag $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    displayName: Docker Build

  - script: docker push $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    displayName: Docker Push

  - script: |
      if [[ "$WIZ_ENV" == "app" ]]; then unset WIZ_ENV; fi
      curl --silent -o wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64 && chmod +x wizcli
      ./wizcli auth
    displayName: Wiz CLI Setup
    env:
      WIZ_CLIENT_ID: $(WIZ_CLIENT_ID)
      WIZ_CLIENT_SECRET: $(WIZ_CLIENT_SECRET)
      WIZ_ENV: $WIZ_ENV

  - script: |
      ./wizcli docker scan --image $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG --dockerfile "$(dockerfile-path)/Dockerfile"
      ./wizcli docker tag -S -i $IMAGE_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    displayName: Wiz CLI Scan & Tag
